# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 172964282e83fa6499d7fc3bad97eb1b1aad05e5b46c05082b4bffa132a862b91926ade6f58c59f6dd3864549a02b23b4c74df1ab920faff31021a0c1372cb8e

test:
  secret_key_base: 351d7dbd493b30a7fdef0f3be48d8130ceed19872e73b2b3cab13aa23282bd5d7c9223acb494c753ab54bd52c71f663626e2be77c566ba48f6b92d2b5ebfbc0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
